name: Upload prebuild binaries
on:
  release:
    types: [published]

jobs:
  nightly:
    name: Deploy releases
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [x86_64]
        include:
          # use for 32 bit build
          - os: windows-latest
            arch: x86
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ldc-latest

      - name: dub upgrade
        uses: WebFreak001/dub-upgrade@v0.1.0

      - name: Run tests
        run: dub test

      # Linux release
      - name: Build Linux release
        run: ./ci/build.sh && rdmd ci/validate_version.d
        if: matrix.os == 'ubuntu-latest'
        env:
          ARCH: ${{ matrix.arch }}
          BUILD: release

      - name: Deploy Linux release
        if: matrix.os == 'ubuntu-latest'
        uses: WebFreak001/upload-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS: linux-${{ matrix.arch }}
        with:
          file: ./serve-d.tar.xz
          mime: application/x-gtar
          name: serve-d_${TAG}-${OS}.tar.xz

      # OSX release
      - name: Build OSX release
        run: ./ci/build.sh && rdmd ci/validate_version.d
        if: matrix.os == 'macOS-latest'
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'
          ARCH: ${{ matrix.arch }}
          BUILD: release

      - name: Deploy OSX release
        if: matrix.os == 'macOS-latest'
        uses: WebFreak001/upload-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS: osx-${{ matrix.arch }}
        with:
          file: ./serve-d.tar.xz
          mime: application/x-gtar
          name: serve-d_${TAG}-${OS}.tar.xz

      # Windows release
      - name: Build Windows release
        run: (.\ci\build.bat) -and (rdmd ci\validate_version.d)
        if: matrix.os == 'windows-latest'
        env:
          BUILD: release
          ARCH: ${{ matrix.arch }}

      - name: Deploy Windows release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/upload-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS: windows-${{ matrix.arch }}
        with:
          file: ./serve-d.zip
          mime: application/zip
          name: serve-d_${TAG}-${OS}.zip

      - name: cache dependency binaries
        uses: WebFreak001/dub-upgrade@v0.1.0
        with:
          store: true
